version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2021-09-15T04-54-25Z
    ports:
      - "9000:9000"
    volumes:
      - ./:/data
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniominio
    command: server /data
